import dataclasses
import math
import random
from pathlib import Path

import numpy as np
import pytest

from satsim.config import load_json, transform
from satsim import time
from satsim.passive_rf import core
from satsim.passive_rf.core import db_to_lin
from satsim.passive_rf.config import load_run_config
from satsim.passive_rf.model import (
    receiver_geometry,
    simulate_measurement,
    simulate_run_config,
    stable_measurement_seed,
)
from satsim.passive_rf.types import (
    EstimatorParams,
    ReceiverGeometry,
    ReceiverParams,
    TargetRFParams,
)


CONFIG_PATH = Path(__file__).parent / 'config_passive_rf.json'


def _run_config(**changes):
    document = transform(
        load_json(str(CONFIG_PATH)),
        dirname=str(CONFIG_PATH.parent),
    )
    config = load_run_config(document)
    return dataclasses.replace(config, **changes)


def test_measurement_kernel_matches_prototype_golden_vector():
    """Golden values were generated by the handoff prototype with seed 42."""
    config = _run_config()
    request = config.observations[0]
    target = config.targets[request.target_id]
    satellite = config.target_objects[request.target_id]
    geometries = []
    for receiver_id in (request.sensor1, request.sensor2):
        geometries.append(receiver_geometry(
            config.observers[receiver_id],
            satellite,
            request.time,
        ))
    record = simulate_measurement(
        target,
        config.receivers[request.sensor1],
        config.receivers[request.sensor2],
        config.estimator,
        request.time,
        random.Random(42),
        geometries[0],
        geometries[1],
    )
    assert record['snrRawDb'] == pytest.approx(39.028, abs=0.001)
    assert record['snrProcessedDb'] == pytest.approx(70.008, abs=0.001)
    assert record['snr'] == pytest.approx(db_to_lin(record['snrProcessedDb']))
    assert record['tdoaTrue'] == pytest.approx(0.0009976404761496479, abs=1e-18)
    assert record['fdoaTrue'] == pytest.approx(-1963.8066386465944, abs=1e-10)
    assert record['tdoaUnc'] == pytest.approx(1.20025282457185e-08, rel=1e-14)
    assert record['fdoaUnc'] == pytest.approx(0.0030002107019385265, rel=1e-14)
    assert record['tdoa'] == pytest.approx(0.0009976387467013972, abs=1e-18)
    assert record['fdoa'] == pytest.approx(-1963.8071573938264, abs=1e-10)
    assert record['band'] == 'S-band'
    assert 'seed' not in record
    assert 'sigma_tdoa_s' not in record
    assert 'sigma_fdoa_hz' not in record
    assert 'dataMode' not in record
    assert 'createdAt' not in record

    # The standard SatSim Earth-centered geometry remains within 0.1 ns TDOA
    # and 0.2 mHz FDOA of the private prototype geometry.
    assert record['tdoaTrue'] == pytest.approx(
        0.0009976405262695578,
        abs=1.0e-10,
    )
    assert record['fdoaTrue'] == pytest.approx(
        -1963.8067461204773,
        abs=2.0e-4,
    )


def test_native_measurement_seed_is_repeatable():
    config = _run_config()
    first = simulate_run_config(config)
    second = simulate_run_config(config)
    assert first == second
    assert all(record['type'] == 'PASSIVE_RF' for record in first)
    assert all(record['uct'] is False for record in first)
    assert all('seed' not in record for record in first)


def test_unrelated_insertion_does_not_perturb_existing_measurements():
    config = _run_config()
    baseline = simulate_run_config(config)
    original = config.observations[0]
    inserted = dataclasses.replace(
        original,
        time=time.utc_from_list([2020, 1, 29, 13, 9, 59.5], delta_sec=-0.5),
        source_index=999,
    )
    extended = dataclasses.replace(
        config,
        observations=config.observations + (inserted,),
    )
    extended_records = simulate_run_config(extended)
    baseline_by_key = {
        (record['obTime'], record['idSensor1'], record['idSensor2']): record
        for record in baseline
    }
    extended_by_key = {
        (record['obTime'], record['idSensor1'], record['idSensor2']): record
        for record in extended_records
    }
    for key, record in baseline_by_key.items():
        assert extended_by_key[key] == record


def test_duplicate_occurrences_have_distinct_stable_seeds():
    request = _run_config().observations[0]
    duplicate = dataclasses.replace(request, occurrence=1)
    assert stable_measurement_seed(42, request) != stable_measurement_seed(42, duplicate)
    assert stable_measurement_seed(42, request) == stable_measurement_seed(42, request)


def test_fixed_fdoa_convention_tracks_tdoa_time_derivative():
    records = simulate_run_config(_run_config())
    pair = [record for record in records if record['idSensor2'] == 'RX_B']
    pair.sort(key=lambda record: record['obTime'])
    derivative = pair[1]['tdoaTrue'] - pair[0]['tdoaTrue']
    expected_midpoint_fdoa = 2.2e9 * derivative
    actual_midpoint_fdoa = 0.5 * (pair[0]['fdoaTrue'] + pair[1]['fdoaTrue'])
    assert actual_midpoint_fdoa == pytest.approx(expected_midpoint_fdoa, abs=0.01)


@pytest.mark.parametrize(('blocked_receiver', 'remaining_pair'), [
    ('RX_A', ('RX_B', 'RX_C')),
    ('RX_C', ('RX_A', 'RX_B')),
])
def test_field_of_view_filters_pairs_at_both_receivers(
    monkeypatch,
    blocked_receiver,
    remaining_pair,
):
    import satsim.passive_rf.model as model

    def geometry(observer, *args, **kwargs):
        elevation = -5.0 if observer == blocked_receiver else 45.0
        return ReceiverGeometry(1.0e6, 0.0, 45.0, elevation)

    monkeypatch.setattr(
        model,
        'receiver_geometry',
        geometry,
    )
    config = _run_config()
    receivers = {
        name: dataclasses.replace(
            receiver,
            az_limits=(0.0, 360.0),
            el_limits=(0.0, 90.0),
        )
        for name, receiver in config.receivers.items()
    }
    config = dataclasses.replace(config, receivers=receivers)
    records = simulate_run_config(
        config,
        target_objects={25544: object()},
        observer_objects={name: name for name in config.receivers},
    )
    assert {
        (record['idSensor1'], record['idSensor2'])
        for record in records
    } == {remaining_pair}


def test_field_of_view_filters_azimuth(monkeypatch):
    import satsim.passive_rf.model as model

    monkeypatch.setattr(
        model,
        'receiver_geometry',
        lambda *args, **kwargs: ReceiverGeometry(1.0e6, 0.0, 181.0, 45.0),
    )
    config = _run_config()
    receivers = {
        name: dataclasses.replace(
            receiver,
            az_limits=(0.0, 180.0),
            el_limits=(0.0, 90.0),
        )
        for name, receiver in config.receivers.items()
    }
    config = dataclasses.replace(config, receivers=receivers)
    assert simulate_run_config(
        config,
        target_objects={25544: object()},
        observer_objects={name: name for name in config.receivers},
    ) == []


def test_db_conversions_round_trip():
    assert core.db_to_lin(10.0) == pytest.approx(10.0)
    assert core.lin_to_db(10.0) == pytest.approx(10.0)
    assert core.lin_to_db(core.db_to_lin(-17.3)) == pytest.approx(-17.3)


@pytest.mark.parametrize('value', [0.0, -1.0, math.inf, math.nan])
def test_lin_to_db_rejects_invalid_values(value):
    with pytest.raises(ValueError, match='positive and finite'):
        core.lin_to_db(value)


def test_fspl_matches_closed_form_and_rejects_invalid_values():
    expected = 20.0 * math.log10(
        4.0 * math.pi * 1.0e6 * 2.2e9 / core.C_M_S
    )
    assert core.fspl_db(2.2e9, 1.0e6) == pytest.approx(expected)
    with pytest.raises(ValueError, match='Range'):
        core.fspl_db(2.2e9, 0.0)
    with pytest.raises(ValueError, match='Frequency'):
        core.fspl_db(0.0, 1.0)


def test_noise_power():
    expected = 10.0 * math.log10(core.K_B * 290.0 * 1.0e6)
    assert core.noise_power_dbw(1.0e6, 0.0, 290.0) == pytest.approx(expected)
    with pytest.raises(ValueError, match='Bandwidth'):
        core.noise_power_dbw(0.0, 0.0)


def test_effective_pair_snr_and_processing_gain():
    assert core.effective_snr_db(20.0, 20.0) == pytest.approx(
        20.0 - 10.0 * math.log10(2.0)
    )
    assert core.processing_gain_db(500000.0, 0.005) == pytest.approx(
        10.0 * math.log10(2500.0)
    )
    with pytest.raises(ValueError, match='positive'):
        core.processing_gain_db(1.0, 0.0)


@pytest.mark.parametrize('rect', [True, False])
def test_uncertainty_models_are_positive(rect):
    tdoa, fdoa = core.tdoa_fdoa_uncertainties(
        500000.0, 15.0, 1.0, rect
    )
    assert tdoa > 0.0
    assert fdoa > 0.0


def test_site_link_snr():
    target = TargetRFParams(1, 2.2e9, 500000.0, 45.0)
    receiver = ReceiverParams('A', 30.0, 2.0, 1.0, 290.0)
    expected = (
        45.0 + 30.0 - core.fspl_db(2.2e9, 4.0e7) - 1.0 -
        core.noise_power_dbw(500000.0, 2.0, 290.0)
    )
    assert core.receiver_snr_db(target, receiver, 4.0e7) == pytest.approx(expected)


def test_estimator_uses_max_pair_level_override():
    target = TargetRFParams(1, 2.2e9, 500000.0, 45.0)
    estimator = EstimatorParams(
        tdoa_floor_s=1e-9,
        fdoa_floor_hz=1e-3,
        tdoa_floor_by_sensor={'A': 2e-8, 'B': 1e-8},
        fdoa_floor_by_sensor={'A': 0.02, 'B': 0.01},
    )
    tdoa, fdoa = core.measurement_uncertainties(
        target, estimator, 'A', 'B', 100.0
    )
    assert tdoa >= 2e-8
    assert fdoa >= 0.02
    np.testing.assert_allclose(
        core.combine_sensor_value(1.0, {'A': 2.0, 'B': 3.0}, 'A', 'B'),
        3.0,
    )


def test_standard_satsim_target_observer_and_los_geometry():
    config = _run_config()
    request = config.observations[0]
    target = config.target_objects[request.target_id]
    observer = config.observers[request.sensor1]

    geometry = receiver_geometry(observer, target, request.time)

    assert geometry.range_m > 0.0
    assert abs(geometry.range_rate_m_s) < 20000.0
    assert 0.0 <= geometry.azimuth_deg <= 360.0
    assert -90.0 <= geometry.elevation_deg <= 90.0


def test_run_resolves_standard_geometry_once_per_target_receiver_epoch(monkeypatch):
    import satsim.passive_rf.model as model

    config = _run_config()
    geometry_calls = []

    def build_geometry(observer, target, t):
        geometry_calls.append((observer, target, t.utc_iso()))
        return ReceiverGeometry(1.0e6, 0.0, 45.0, -45.0)

    monkeypatch.setattr(model, 'receiver_geometry', build_geometry)

    records = simulate_run_config(
        config,
        target_objects={25544: 'target'},
        observer_objects={name: name for name in config.receivers},
    )

    assert len(geometry_calls) == 6
    assert len(records) == 6
